"""Human-readable portfolio reports for AgentBench experiment results."""

from __future__ import annotations

from typing import Any


def _pct(value: Any) -> str:
    try:
        return f"{float(value) * 100:.1f}%"
    except (TypeError, ValueError):
        return "n/a"


def _number(value: Any, digits: int = 2) -> str:
    if value is None:
        return "n/a"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return str(value)
    if numeric.is_integer():
        return str(int(numeric))
    return f"{numeric:.{digits}f}"


def render_markdown_report(report: dict[str, Any]) -> str:
    """Render a compact, reviewer-friendly benchmark report."""

    suite = report.get("suite", {})
    experiment = report.get("experiment", {})
    summary = report.get("summary", {})
    overall = summary.get("overall", {})
    lock = report.get("lock", {})

    title = suite.get("name") or suite.get("id") or experiment.get("name") or "AgentBench Report"
    lines = [
        f"# {title}",
        "",
        "> Reproducible coding-agent benchmark generated by AgentBench.",
        "",
        "## Result",
        "",
        f"- **Experiment status:** {experiment.get('status', 'unknown')}",
        f"- **Planned runs:** {_number(overall.get('planned_runs', experiment.get('planned_runs')))}",
        f"- **Benchmark runs:** {_number(overall.get('benchmark_runs'))}",
        f"- **Success rate:** {_pct(overall.get('success_rate'))}",
        f"- **Completion rate:** {_pct(overall.get('completion_rate'))}",
        f"- **Orchestration errors:** {_number(overall.get('orchestration_errors'))}",
        f"- **Tests passed:** {_number(overall.get('tests_passed'))}",
        f"- **Tests failed:** {_number(overall.get('tests_failed'))}",
    ]

    runtime = overall.get("runtime_seconds", {}) or {}
    if runtime:
        lines.extend(
            [
                f"- **Average runtime:** {_number(runtime.get('average'))} s",
                f"- **Total runtime:** {_number(runtime.get('total'))} s",
            ]
        )

    if lock:
        lines.extend(
            [
                "",
                "## Reproducibility",
                "",
                f"- **Suite manifest SHA-256:** `{suite.get('manifest_sha256', 'n/a')}`",
                f"- **Lock identity SHA-256:** `{lock.get('identity_sha256', 'n/a')}`",
                f"- **Lock schema:** {lock.get('lock_schema_version', 'n/a')}",
            ]
        )

    by_agent = summary.get("by_agent", []) or []
    if by_agent:
        lines.extend(
            [
                "",
                "## Agent comparison",
                "",
                "| Agent | Success | Runs | Avg runtime | Tests passed | Files changed |",
                "|---|---:|---:|---:|---:|---:|",
            ]
        )
        for row in by_agent:
            metrics = row.get("metrics", {}) or {}
            agent_runtime = metrics.get("runtime_seconds", {}) or {}
            changes = metrics.get("changes", {}) or {}
            lines.append(
                "| {agent} | {success} | {runs} | {runtime} s | {tests} | {files} |".format(
                    agent=row.get("agent_name", row.get("agent_config_id", "unknown")),
                    success=_pct(metrics.get("success_rate")),
                    runs=_number(metrics.get("benchmark_runs")),
                    runtime=_number(agent_runtime.get("average")),
                    tests=_number(metrics.get("tests_passed")),
                    files=_number(changes.get("files_changed_total")),
                )
            )

    by_task = summary.get("by_task", []) or []
    if by_task:
        lines.extend(
            [
                "",
                "## Task breakdown",
                "",
                "| Task | Success | Runs | Orchestration errors |",
                "|---|---:|---:|---:|",
            ]
        )
        for row in by_task:
            metrics = row.get("metrics", {}) or {}
            lines.append(
                "| {task} | {success} | {runs} | {errors} |".format(
                    task=row.get("task_name", row.get("task_id", "unknown")),
                    success=_pct(metrics.get("success_rate")),
                    runs=_number(metrics.get("benchmark_runs")),
                    errors=_number(metrics.get("orchestration_errors")),
                )
            )

    lines.extend(
        [
            "",
            "## Integrity model",
            "",
            "Each run starts from a pinned Git commit in an isolated detached worktree. "
            "Agent evidence is captured before tests, artifacts are write-once, process "
            "timeouts are bounded, and suite replay can reject provenance drift.",
            "",
            "---",
            "",
            "Generated by **AgentBench**.",
            "",
        ]
    )
    return "\n".join(lines)


__all__ = ["render_markdown_report"]
