"""Human-readable portfolio reports for AgentBench experiments."""

from __future__ import annotations

from typing import Any


def _pct(value: Any) -> str:
    if value is None:
        return "n/a"
    try:
        return f"{float(value) * 100:.1f}%"
    except (TypeError, ValueError):
        return "n/a"


def _number(value: Any, digits: int = 2) -> str:
    if value is None:
        return "n/a"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return str(value)
    if numeric.is_integer():
        return str(int(numeric))
    return f"{numeric:.{digits}f}"


def _interval(value: Any, *, percent: bool = False) -> str:
    if not isinstance(value, dict):
        return "n/a"
    low = value.get("low")
    high = value.get("high")
    if low is None or high is None:
        return "n/a"
    if percent:
        return f"{float(low) * 100:.1f}%–{float(high) * 100:.1f}%"
    return f"{_number(low)}–{_number(high)}"


def render_leaderboard_markdown(
    summary: dict[str, Any],
    title: str = "AgentBench Leaderboard",
) -> str:
    """Render the V2 conservative leaderboard and pairwise task comparison."""

    ranking = summary.get("ranking", {}) or {}
    entries = ranking.get("entries", []) or []
    lines = [
        f"# {title}",
        "",
        "## Conservative ranking",
        "",
        "| Rank | Agent | Reliability | Success | 95% success CI | Median runtime | Avg tokens |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ]
    if entries:
        for row in entries:
            lines.append(
                "| {rank} | {agent} | {reliability} | {success} | {ci} | {runtime} s | {tokens} |".format(
                    rank=row.get("rank", "n/a"),
                    agent=row.get("agent_name", "unknown"),
                    reliability=_pct(row.get("reliability_score")),
                    success=_pct(row.get("success_rate")),
                    ci=_interval(
                        row.get("success_rate_confidence_interval_95"),
                        percent=True,
                    ),
                    runtime=_number(row.get("median_runtime_seconds")),
                    tokens=_number(row.get("average_tokens")),
                )
            )
    else:
        lines.append("| — | No ranked agents | — | — | — | — | — |")

    lines.extend(
        [
            "",
            f"**Method:** {ranking.get('description', 'No ranking methodology available.')}",
        ]
    )

    pairwise = summary.get("pairwise_task_comparison", []) or []
    if pairwise:
        lines.extend(
            [
                "",
                "## Pairwise task outcomes",
                "",
                "| Agent A | Agent B | A wins | B wins | Ties | Mean Δ success | Exact sign p | Tasks |",
                "|---|---|---:|---:|---:|---:|---:|---:|",
            ]
        )
        for row in pairwise:
            lines.append(
                "| {left} | {right} | {wins} | {losses} | {ties} | {delta} | {pvalue} | {tasks} |".format(
                    left=row.get("left_agent_name", "unknown"),
                    right=row.get("right_agent_name", "unknown"),
                    wins=row.get("left_task_wins", 0),
                    losses=row.get("right_task_wins", 0),
                    ties=row.get("ties", 0),
                    delta=_pct(row.get("mean_success_rate_difference")),
                    pvalue=_number(
                        ((row.get("exact_sign_test") or {}).get("p_value")),
                        digits=4,
                    ),
                    tasks=row.get("tasks_compared", 0),
                )
            )

    lines.extend(
        [
            "",
            "> Pairwise wins compare observed task success rates only. Ties remain ties; "
            "runtime is not used to manufacture a quality win. V3 also reports "
            "an exact two-sided sign test over decisive tasks; it is descriptive "
            "and is not used by the ranking.",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown_report(report: dict[str, Any]) -> str:
    """Render a reviewer-friendly V2 benchmark report."""

    suite = report.get("suite", {})
    experiment = report.get("experiment", {})
    summary = report.get("summary", {})
    overall = summary.get("overall", {})
    lock = report.get("lock", {})
    statistics = overall.get("statistics", {}) or {}
    pack = suite.get("benchmark_pack") or {}

    title = (
        suite.get("name")
        or suite.get("id")
        or experiment.get("name")
        or "AgentBench Report"
    )
    lines = [
        f"# {title}",
        "",
        "> Reproducible coding-agent benchmark generated by AgentBench V3.",
        "",
    ]

    if pack:
        lines.extend(
            [
                "## Benchmark corpus",
                "",
                f"- **Pack:** {pack.get('id', 'n/a')} {pack.get('version', '')}".rstrip(),
                f"- **Description:** {pack.get('description', 'n/a')}",
                "",
            ]
        )

    lines.extend(
        [
            "## Result",
            "",
            f"- **Experiment status:** {experiment.get('status', 'unknown')}",
            f"- **Planned runs:** {_number(overall.get('planned_runs', experiment.get('planned_runs')))}",
            f"- **Benchmark runs:** {_number(overall.get('benchmark_runs'))}",
            f"- **Success rate:** {_pct(overall.get('success_rate'))}",
            (
                "- **95% success interval:** "
                + _interval(
                    statistics.get("success_rate_confidence_interval_95"),
                    percent=True,
                )
            ),
            f"- **Completion rate:** {_pct(overall.get('completion_rate'))}",
            f"- **Orchestration errors:** {_number(overall.get('orchestration_errors'))}",
            f"- **Tests passed:** {_number(overall.get('tests_passed'))}",
            f"- **Tests failed:** {_number(overall.get('tests_failed'))}",
        ]
    )

    runtime = overall.get("runtime_seconds", {}) or {}
    if runtime:
        lines.extend(
            [
                f"- **Median runtime:** {_number(runtime.get('median'))} s",
                f"- **Average runtime:** {_number(runtime.get('average'))} s",
                f"- **Runtime mean 95% CI:** {_interval(runtime.get('confidence_interval_95'))} s",
                f"- **Total runtime:** {_number(runtime.get('total'))} s",
            ]
        )

    tokens = overall.get("tokens", {}) or {}
    if tokens.get("measurements"):
        lines.extend(
            [
                f"- **Token coverage:** {_pct(tokens.get('coverage_rate'))}",
                f"- **Average measured tokens:** {_number(tokens.get('average'))}",
                f"- **Median measured tokens:** {_number(tokens.get('median'))}",
            ]
        )

    if lock:
        lines.extend(
            [
                "",
                "## Reproducibility",
                "",
                f"- **Suite manifest SHA-256:** `{suite.get('manifest_sha256', 'n/a')}`",
                f"- **Lock identity SHA-256:** `{lock.get('identity_sha256', 'n/a')}`",
                f"- **Lock schema:** {lock.get('lock_schema_version', 'n/a')}",
            ]
        )

    ranking_md = render_leaderboard_markdown(summary, title="Leaderboard")
    lines.extend(["", ranking_md])

    by_agent = summary.get("by_agent", []) or []
    if by_agent:
        lines.extend(
            [
                "",
                "## Agent measurements",
                "",
                "| Agent | Success | 95% CI | Runs | Median runtime | Tests passed | Files changed |",
                "|---|---:|---:|---:|---:|---:|---:|",
            ]
        )
        for row in by_agent:
            metrics = row.get("metrics", {}) or {}
            agent_runtime = metrics.get("runtime_seconds", {}) or {}
            changes = metrics.get("changes", {}) or {}
            agent_stats = metrics.get("statistics", {}) or {}
            lines.append(
                "| {agent} | {success} | {ci} | {runs} | {runtime} s | {tests} | {files} |".format(
                    agent=row.get("agent_name", row.get("agent_config_id", "unknown")),
                    success=_pct(metrics.get("success_rate")),
                    ci=_interval(
                        agent_stats.get("success_rate_confidence_interval_95"),
                        percent=True,
                    ),
                    runs=_number(metrics.get("benchmark_runs")),
                    runtime=_number(agent_runtime.get("median")),
                    tests=_number(metrics.get("tests_passed")),
                    files=_number(changes.get("files_changed_total")),
                )
            )

    by_task = summary.get("by_task", []) or []
    if by_task:
        lines.extend(
            [
                "",
                "## Task breakdown",
                "",
                "| Task | Success | 95% CI | Runs | Orchestration errors |",
                "|---|---:|---:|---:|---:|",
            ]
        )
        for row in by_task:
            metrics = row.get("metrics", {}) or {}
            task_stats = metrics.get("statistics", {}) or {}
            lines.append(
                "| {task} | {success} | {ci} | {runs} | {errors} |".format(
                    task=row.get("task_name", row.get("task_id", "unknown")),
                    success=_pct(metrics.get("success_rate")),
                    ci=_interval(
                        task_stats.get("success_rate_confidence_interval_95"),
                        percent=True,
                    ),
                    runs=_number(metrics.get("benchmark_runs")),
                    errors=_number(metrics.get("orchestration_errors")),
                )
            )

    lines.extend(
        [
            "",
            "## Statistical interpretation",
            "",
            "Success-rate intervals use the two-sided 95% Wilson score interval. "
            "Mean runtime/token/change intervals use a two-sided 95% Student-t "
            "interval when at least two measurements exist. Pairwise task outcomes "
            "also report an exact two-sided sign test over decisive tasks. The "
            "leaderboard uses "
            "the lower Wilson success bound as a conservative reliability score. "
            "These summaries describe the observed repeated trials; AgentBench does "
            "not claim that repetitions are independent or that rank differences are "
            "statistically significant.",
            "",
            "## Integrity model",
            "",
            "Each run starts from a pinned Git commit in an isolated detached worktree. "
            "Agent evidence is captured before tests, artifacts are write-once, process "
            "timeouts are bounded, and suite replay can reject provenance drift.",
            "",
            "---",
            "",
            "Generated by **AgentBench V3**.",
            "",
        ]
    )
    return "\n".join(lines)


__all__ = ["render_leaderboard_markdown", "render_markdown_report"]
